name: Build Autoreduction
description: Build Autoreduction in a test environment

runs:
  using: composite

  steps:
    - name: Install Autoreduction
      run: |
        python -m pip install --upgrade pip
        pip install -e .
      shell: bash

    - name: Install test suite dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Setup test environment
      run: |
        autoreduce-creds-migrate
        # Externals must be after test_settings
        python setup.py externals -s activemq
        PYTHONPATH=. python WebApp/autoreduce_webapp/manage.py migrate
        cat build.log
        _LOCAL_PYTHON_PATH=$(which python)
        sudo $_LOCAL_PYTHON_PATH setup.py start
        python WebApp/autoreduce_webapp/manage.py collectstatic
      shell: bash
