name: Build Autoreduction
description: Build Autoreduction in a test environment

runs:
  using: composite

  steps:
    - name: Install Autoreduction
      run: |
        python -m pip install --upgrade pip
        pip install -e .
      shell: bash

    - name: Install test suite dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Setup test environment
      run: |
        autoreduce-creds-migrate
        # Externals must be after test_settings
        docker run --name activemq -p 61613:61613 -p 8161:8161 -it rmohr/activemq
        PYTHONPATH=. python autoreduce_qp/manage.py migrate
        cat build.log
        _LOCAL_PYTHON_PATH=$(which python)
      shell: bash
